/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
// package hotel_management_system;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.awt.event.MouseEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author admin
 */
public class Employee_Out extends javax.swing.JFrame {

    /**
     * Creates new form Employee_Out
     */
    public Employee_Out(String name) {
        initComponents(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String Manager_name) {

        Status = new javax.swing.ButtonGroup();
        manu = new javax.swing.JPanel();
        lStaffIn = new javax.swing.JLabel();
        lStaffOut = new javax.swing.JLabel();
        lHome = new javax.swing.JLabel();
        lStaffUpdate = new javax.swing.JLabel();
        EmployeePanel2 = new javax.swing.JPanel();
        lname = new javax.swing.JLabel();
        lemail = new javax.swing.JLabel();
        lphone = new javax.swing.JLabel();
        ljob = new javax.swing.JLabel();
        lsalary = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        temail = new javax.swing.JTextField();
        tName = new javax.swing.JTextField();
        tsalary = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        tName1 = new javax.swing.JTextField();
        lStatus = new javax.swing.JLabel();
        Active = new javax.swing.JRadioButton();
        In_Active = new javax.swing.JRadioButton();
        bgimg2 = new javax.swing.JLabel();
        bgimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manu.setBackground(new java.awt.Color(255, 102, 51));

        lStaffIn.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lStaffIn.setForeground(new java.awt.Color(255, 255, 255));
        lStaffIn.setText("Staff In");
        lStaffIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lStaffInMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lStaffInMouseClicked(me,Manager_name);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lStaffInMouseExited(me);
            }
        });

        lStaffOut.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lStaffOut.setForeground(new java.awt.Color(255, 255, 255));
        lStaffOut.setText("Staff Out");
        lStaffOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));
        lStaffOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lStaffOutMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lStaffOutMouseClicked(me,Manager_name);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lStaffOutMouseExited(me);
            }
        });

        lHome.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lHome.setForeground(new java.awt.Color(255, 255, 255));
        lHome.setText("Home");
        lHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lHomeMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lHomeMouseClicked(me,Manager_name);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lHomeMouseExited(me);
            }
        });

        lStaffUpdate.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lStaffUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lStaffUpdate.setText("Staff Update");
        lStaffUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lStaffUpdateMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lStaffUpdateMouseClicked(me,Manager_name);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lStaffUpdateMouseExited(me);
            }
        });

        javax.swing.GroupLayout manuLayout = new javax.swing.GroupLayout(manu);
        manu.setLayout(manuLayout);
        manuLayout.setHorizontalGroup(
            manuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 489, Short.MAX_VALUE)
                .addComponent(lStaffIn)
                .addGap(110, 110, 110)
                .addComponent(lStaffUpdate)
                .addGap(103, 103, 103)
                .addComponent(lStaffOut)
                .addGap(59, 59, 59))
        );
        manuLayout.setVerticalGroup(
            manuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(manuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStaffIn)
                    .addComponent(lStaffOut)
                    .addComponent(lHome)
                    .addComponent(lStaffUpdate))
                .addContainerGap())
        );

        getContentPane().add(manu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 40));

        EmployeePanel2.setBackground(new java.awt.Color(153, 204, 255));
        EmployeePanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lname.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lname.setText("Name :-");

        lemail.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lemail.setText("Email :-");

        lphone.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lphone.setText("Phone : -");

        ljob.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        ljob.setText("Job :-");

        lsalary.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lsalary.setText("Salary :-");

        phone.setBackground(new java.awt.Color(153, 204, 255));
        phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneKeyReleased(evt);
            }
        });
        phone.setEditable(false);

        temail.setBackground(new java.awt.Color(153, 204, 255));
        temail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        temail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                temailKeyReleased(evt);
            }
        });

        tName.setBackground(new java.awt.Color(153, 204, 255));
        tName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tNameKeyReleased(evt);
            }
        });

        tsalary.setBackground(new java.awt.Color(153, 204, 255));
        tsalary.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tsalaryKeyReleased(evt);
            }
        });
        tsalary.setEditable(false);

        Delete.setBackground(new java.awt.Color(255, 102, 51));
        Delete.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.setBorder(null);
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent ae) {
                DeleteActioPerformed(ae);
            }
        });

        tName1.setBackground(new java.awt.Color(153, 204, 255));
        tName1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tName1KeyReleased(evt);
            }
        });
        tName1.setEditable(false);


        lStatus.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lStatus.setText("Status:-");

        Active.setBackground(new java.awt.Color(153, 204, 255));
        Status.add(Active);
        Active.setText("Active");
        

        In_Active.setBackground(new java.awt.Color(153, 204, 255));
        Status.add(In_Active);
        In_Active.setText("In-Active");

        javax.swing.GroupLayout EmployeePanel2Layout = new javax.swing.GroupLayout(EmployeePanel2);
        EmployeePanel2.setLayout(EmployeePanel2Layout);
        EmployeePanel2Layout.setHorizontalGroup(
            EmployeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(EmployeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeePanel2Layout.createSequentialGroup()
                        .addGroup(EmployeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lphone, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(EmployeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ljob, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tName1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EmployeePanel2Layout.createSequentialGroup()
                        .addGroup(EmployeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeePanel2Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(lemail, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(EmployeePanel2Layout.createSequentialGroup()
                        .addComponent(Active)
                        .addGap(34, 34, 34)
                        .addComponent(In_Active)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        EmployeePanel2Layout.setVerticalGroup(
            EmployeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(EmployeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lemail)
                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(EmployeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname)
                    .addComponent(ljob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lphone)
                    .addComponent(lsalary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmployeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lStatus)
                .addGap(0, 0, 0)
                .addGroup(EmployeePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Active)
                    .addComponent(In_Active)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(EmployeePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 580, 260));

        bgimg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/staff2.jpg"))); // NOI18N
        getContentPane().add(bgimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 580, 143));

        bgimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/Bg Image.jpeg"))); // NOI18N
        getContentPane().add(bgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void DeleteActioPerformed(ActionEvent ae) {
        if(tsalary.getText().equals("")) {
            JOptionPane.showMessageDialog(Delete, "Enter Email", "Email", JOptionPane.WARNING_MESSAGE);
        }
        else {
            try {
                Connection con = new dbConnection().getDbconnection();
                Statement stm = con.createStatement();
                String q = "delete from employee_details where email= "+temail.getText()+"";
                int x = stm.executeUpdate(q);
                if(x!=0) {
                    JOptionPane.showMessageDialog(Delete, "deleted Done", "Fine", JOptionPane.PLAIN_MESSAGE);
                }
                else {
                    JOptionPane.showMessageDialog(Delete, "Not Deleted ", "Something wrong", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                //TODO: handle exception
            }
        }
    }

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
        // TODO add your handling code here:
        String phoneNo = phone.getText();
        int phNo = phoneNo.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9'){
            if(phNo < 10){
                phone.setEditable(true);
            }else {
                phone.setEditable(false);
                phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
            }
        }else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                phone.setEditable(true);
            }else{
                phone.setEditable(false);
                phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            }
        }
    }//GEN-LAST:event_phoneKeyPressed

    private void phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyReleased
        // TODO add your handling code here:
        //        String PATTERN = "^[0-9]{10}$";
        //        Pattern patt = Pattern.compile(PATTERN);
        //        Matcher match = patt.matcher(phone.getText());
        //        if (!match.matches()) {
            //            phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            //        } else {
            //                phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
            //        }
    }//GEN-LAST:event_phoneKeyReleased

    private void temailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temailKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(temail.getText());
        if (!match.matches()) {
            tName.setText("");
            phone.setText("");
            tName1.setText("");
            tsalary.setText("");
            Active.setSelected(false);
            In_Active.setSelected(false);
            temail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));

        } else {
            temail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
            try {
                Connection con = new dbConnection().getDbconnection();
                Statement stm = con.createStatement();
                String q = "select name,phone,job_role,salary,status from employee_details where email='"+temail.getText()+"'";
                ResultSet rs= stm.executeQuery(q);
                if(rs.next()) {
                    tName.setText(rs.getString("name"));
                    phone.setText(rs.getString("phone"));
                    tName1.setText(rs.getString("job_role"));
                    tsalary.setText(Double.toString(rs.getDouble("salary")));
                    boolean statusc = rs.getBoolean("status");
                    if(statusc==true) {
                        Active.setSelected(true);
                    }
                    else {
                        In_Active.setSelected(true);
                    }
                }
                // else {
                //     JOptionPane.showMessageDialog(temail, "Such Record Not found", "Not Found", JOptionPane.WARNING_MESSAGE);
                // }
            } catch (Exception e) {
                //TODO: handle exception
            }
        }
    }//GEN-LAST:event_temailKeyReleased

    private void tNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z\\s]{5,20}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(tName.getText());
        if (!match.matches()) {
            tName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
        } else {
            tName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        }
    }//GEN-LAST:event_tNameKeyReleased

    private void tsalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsalaryKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{4,}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(tsalary.getText());
        if (!match.matches()) {
            tsalary.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
        } else {
            tsalary.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        }
    }//GEN-LAST:event_tsalaryKeyReleased

    private void tName1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tName1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tName1KeyReleased


    // staff update here
    protected void lStaffUpdateMouseExited(MouseEvent me) {
        lStaffUpdate.setForeground(java.awt.Color.white);
        lStaffUpdate.setBorder(null);
    }

    protected void lStaffUpdateMouseClicked(MouseEvent me,String name) {
        if(me.getSource()==lStaffUpdate) {
            dispose();
            new Employee_Update(name).setVisible(true);
        }
    }

    protected void lStaffUpdateMouseEnterd(MouseEvent e) {
        lStaffUpdate.setForeground(new java.awt.Color(126,90,200));
        lStaffUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.black));
    }

    // l home here
    protected void lHomeMouseExited(MouseEvent me) {
        lHome.setForeground(java.awt.Color.white);
        lHome.setBorder(null);
    }

    protected void lHomeMouseClicked(MouseEvent me,String name) {
        if(me.getSource()==lHome) {
            dispose();
            new Manager_Home(name).setVisible(true);
        }
    }

    protected void lHomeMouseEnterd(MouseEvent e) {
        lHome.setForeground(new java.awt.Color(126,90,200));
        lHome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.black));
    }

    // l Staff Out here
    protected void lStaffOutMouseExited(MouseEvent me) {
        lStaffOut.setForeground(java.awt.Color.white);
        lStaffOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));
    }

    protected void lStaffOutMouseClicked(MouseEvent me, String name) {
        // if(me.getSource()==lStaffOut) {
        //     dispose();
        //     new Employee_Out(name).setVisible(true);
        // }
    }

    protected void lStaffOutMouseEnterd(MouseEvent e) {
        lStaffOut.setForeground(new java.awt.Color(126,90,200));
        lStaffOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.black));
    }

    // Staff In here
    protected void lStaffInMouseExited(MouseEvent me) {
        lStaffIn.setForeground(java.awt.Color.white);
        lStaffIn.setBorder(null);
    }

    protected void lStaffInMouseClicked(MouseEvent me,String name) {
        if(me.getSource()==lStaffIn) {
            dispose();
            new employee(name).setVisible(true);
        }
    }

    protected void lStaffInMouseEnterd(MouseEvent e) {
        lStaffIn.setForeground(new java.awt.Color(126,90,200));
        lStaffIn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.black));
    }

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(Employee_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(Employee_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(Employee_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(Employee_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new Employee_Out("name").setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Active;
    private javax.swing.JButton Delete;
    private javax.swing.JPanel EmployeePanel2;
    private javax.swing.JRadioButton In_Active;
    private javax.swing.ButtonGroup Status;
    private javax.swing.JLabel bgimg;
    private javax.swing.JLabel bgimg2;
    private javax.swing.JLabel lHome;
    private javax.swing.JLabel lStaffIn;
    private javax.swing.JLabel lStaffOut;
    private javax.swing.JLabel lStaffUpdate;
    private javax.swing.JLabel lStatus;
    private javax.swing.JLabel lemail;
    private javax.swing.JLabel ljob;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lphone;
    private javax.swing.JLabel lsalary;
    private javax.swing.JPanel manu;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tName1;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tsalary;
    // End of variables declaration//GEN-END:variables
}
