/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
// package login_register;

import java.io.*;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author admin
 */
public class Login_Form extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
    boolean email=false,passwword1=false;
    public Login_Form(String name) {
        initComponents(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String Manager_name) {

        Login_Panel = new javax.swing.JPanel();
        login_img = new javax.swing.JLabel();
        lemail = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lpass = new javax.swing.JLabel();
        tpass = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        forget_label = new javax.swing.JLabel();
        header2 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        header1 = new javax.swing.JPanel();
        lhome = new javax.swing.JLabel();
        lsignup = new javax.swing.JLabel();
        lcustomerLogin = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_Panel.setBackground(new java.awt.Color(153, 204, 255));

        login_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/Login_img.jpeg"))); // NOI18N
        login_img.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        login_img.setAlignmentY(0.0F);

        lemail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lemail.setText("Email:-");

        jTextField1.setBackground(new java.awt.Color(153, 204, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent ke) {
                tTextField1keyReleased(ke);
            }
        });

        lpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lpass.setText("Password:-");

        tpass.setBackground(new java.awt.Color(153, 204, 255));
        tpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent ke) {
                tpasskeyReleased(ke);
            }
        });

        login.setBackground(new java.awt.Color(255, 153, 0));
        login.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt,Manager_name);
            }
        });

        forget_label.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        forget_label.setForeground(new java.awt.Color(255, 0, 0));
        forget_label.setText("Forget Passwrd?");
        forget_label.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 0)));
        forget_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                forget_labelMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                forget_labelMouseClicked(me,Manager_name);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                forget_labelMouseExited(me);
            }
        });


        javax.swing.GroupLayout Login_PanelLayout = new javax.swing.GroupLayout(Login_Panel);
        Login_Panel.setLayout(Login_PanelLayout);
        Login_PanelLayout.setHorizontalGroup(
            Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_PanelLayout.createSequentialGroup()
                .addComponent(login_img)
                .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Login_PanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lemail, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lpass)
                            .addComponent(tpass, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Login_PanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(forget_label)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        Login_PanelLayout.setVerticalGroup(
            Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_PanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lemail)
                .addGap(0, 0, 0)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lpass)
                .addGap(0, 0, 0)
                .addComponent(tpass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forget_label)
                .addContainerGap(35, Short.MAX_VALUE))
            .addComponent(login_img, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        getContentPane().add(Login_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 560, 240));

        header2.setBackground(new java.awt.Color(255, 102, 51));

        heading.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Customer Login ");

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2Layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(heading)
                .addGap(172, 172, 172))
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(heading)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 560, 50));

        header1.setBackground(new java.awt.Color(255, 102, 51));

        lhome.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lhome.setForeground(new java.awt.Color(255, 255, 255));
        lhome.setText("Home");
        lhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lhomeMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lhomeMouseClicked(me,Manager_name);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lhomeMouseExited(me);
            }
        });

        lsignup.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lsignup.setForeground(new java.awt.Color(255, 255, 255));
        lsignup.setText("SignUp");
        lsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lsignupMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lsignupMouseClicked(me,Manager_name);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lsignupMouseExited(me);
            }
        });

        lcustomerLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lcustomerLogin.setForeground(new java.awt.Color(255, 255, 255));
        lcustomerLogin.setText("Customer Login");

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lcustomerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 629, Short.MAX_VALUE)
                .addComponent(lhome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(lsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lhome)
                    .addComponent(lsignup)
                    .addComponent(lcustomerLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/Bg Image.jpeg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void loginActionPerformed(ActionEvent evt,String Manager_name) {
        if(jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(login, "Empty Email", "Empty Mail", JOptionPane.WARNING_MESSAGE);
        }
        else if(tpass.getText().equals("")) {
            JOptionPane.showMessageDialog(login, "Empty Password", "Empty Password", JOptionPane.WARNING_MESSAGE);
        }
        else if(email!=true || passwword1!=true) {
            JOptionPane.showMessageDialog(login, "Invalid Password or Email", "Invalid Inputs", JOptionPane.WARNING_MESSAGE);
        }
        else {
            try {
                Connection con = new dbConnection().getDbconnection();
                Statement stm = con.createStatement();
                String q = "select * from customer_details where email='"+jTextField1.getText()+"'";
                ResultSet rs = stm.executeQuery(q);
                if(rs.next()) {
                    final String password1 = rs.getString("password");
                    if(password1.equals(tpass.getText())) {
                        JOptionPane.showMessageDialog(login, "Done", "Found", JOptionPane.PLAIN_MESSAGE);
                        // dispose the & liked to roombooking or customise_room
                        q = "select email,customer_id from room_reservation_details where email='"+jTextField1.getText()+"'";
                        rs = stm.executeQuery(q);
                        if(rs.next()) {
                            if(evt.getSource()==login) {
                                dispose();
                                new Customise_Room(Manager_name,jTextField1.getText()).setVisible(true);
                            }
                        }
                        else {
                            if(evt.getSource()==login) {
                                dispose();
                                new Room_Booking(Manager_name, jTextField1.getText()).setVisible(true);
                            }
                        }

                    }
                    else {
                        JOptionPane.showMessageDialog(login, "Incorrect Password", "Wrong Password", JOptionPane.WARNING_MESSAGE);
                    }
                }
                else {
                    JOptionPane.showMessageDialog(login, "Given Details Are not Found", "Record Not Found", JOptionPane.WARNING_MESSAGE);

                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    protected void tpasskeyReleased(KeyEvent ke) {
        String PATTERN = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&-+=()])(?=\\S+$).{8,20}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(tpass.getText());
        if (!match.matches()) {
            // JOptionPane.showMessageDialog(null, "Please enter the username");
            tpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            passwword1=false;
        } else {
            passwword1=true;
            tpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        }
    }

    protected void tTextField1keyReleased(KeyEvent ke) {
        String PATTERN = "^[_A-Za-z0-9-\\+]{6,30}+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(jTextField1.getText());
        if (!match.matches()) {
            // JOptionPane.showMessageDialog(null, "Please enter the username");
            jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            email=false;

        } else {
            email=true;
            jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        }
    }

    // forget label here
    protected void forget_labelMouseExited(MouseEvent me) {
        forget_label.setForeground(java.awt.Color.red);
        forget_label.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.red));
    }

    protected void forget_labelMouseEnterd(MouseEvent e) {
        forget_label.setForeground(java.awt.Color.blue);
        forget_label.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.blue));
    }

    protected void forget_labelMouseClicked(MouseEvent me, String name) {
        if(me.getSource()==forget_label) {
            dispose();
            new Forget_Pass(name).setVisible(true);
        }
    }

    // sign up label
    protected void lsignupMouseExited(MouseEvent me) {
        lsignup.setForeground(new java.awt.Color(255, 255, 255));
        lsignup.setBorder(null);
    }

    protected void lsignupMouseClicked(MouseEvent me,String name) {
        if(me.getSource()==lsignup) {
            dispose();
            new SignUpForm(name).setVisible(true);
        }
    }

    protected void lsignupMouseEnterd(MouseEvent e) {
        lsignup.setForeground(new java.awt.Color(126,90,200));
        lsignup.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
    }

    // home Label
    protected void lhomeMouseExited(MouseEvent me) {
        lhome.setForeground(new java.awt.Color(255, 255, 255));
        lhome.setBorder(null);
    }

    protected void lhomeMouseClicked(MouseEvent me,String name) {
        if(me.getSource()==lhome) {
            dispose();
            new Manager_Home(name).setVisible(true);
        }
    }

    protected void lhomeMouseEnterd(MouseEvent e) {
        lhome.setForeground(new java.awt.Color(126,90,200));
        lhome.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
    }
    
    
    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>
    //     //</editor-fold>
    //     //</editor-fold>
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new Login_Form().setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login_Panel;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel forget_label;
    private javax.swing.JPanel header1;
    private javax.swing.JPanel header2;
    private javax.swing.JLabel heading;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lcustomerLogin;
    private javax.swing.JLabel lemail;
    private javax.swing.JLabel lhome;
    private javax.swing.JButton login;
    private javax.swing.JLabel login_img;
    private javax.swing.JLabel lpass;
    private javax.swing.JLabel lsignup;
    private javax.swing.JTextField tpass;
    // End of variables declaration//GEN-END:variables
}
