// package hotel_management_system;

import java.awt.Color;
import java.awt.event.MouseEvent;

import javax.swing.JOptionPane;

// import hotel_management_system.Customer_Data;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class Manager_Home extends javax.swing.JFrame {

    /**
     * Creates new form Manager_Home
     * @param name
     */
    public Manager_Home(String name) {
        initComponents(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String Manager_name) {

        bg2 = new javax.swing.JPanel();
        lwelcome = new javax.swing.JLabel();
        lmanager = new javax.swing.JLabel();
        manu = new javax.swing.JPanel();
        lRoomManage = new javax.swing.JLabel();
        lStaffManage = new javax.swing.JLabel();
        lLogOut = new javax.swing.JLabel();
        customer_login = new javax.swing.JLabel();
        customer_signup = new javax.swing.JLabel();
        lCustomerData = new javax.swing.JLabel();
        lHome = new javax.swing.JLabel();
        bgimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg2.setBackground(new java.awt.Color(102, 102, 102, 80));

        lwelcome.setFont(new java.awt.Font("Lucida Calligraphy", 1, 60)); // NOI18N
        lwelcome.setForeground(new java.awt.Color(255, 255, 255));
        lwelcome.setText("Welcome "+Manager_name);
        lwelcome.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lmanager.setFont(new java.awt.Font("Engravers MT", 1, 80)); // NOI18N
        lmanager.setForeground(new java.awt.Color(255, 102, 51));
        lmanager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lmanager.setText("Manager...!");
        lmanager.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lmanager, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(lwelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lmanager)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1080, 650));

        manu.setBackground(new java.awt.Color(255, 102, 51));

        lRoomManage.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lRoomManage.setForeground(new java.awt.Color(255, 255, 255));
        lRoomManage.setText("Room Manage");
        lRoomManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lRoomManageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lRoomManageMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lRoomManageMouseClicked(me,Manager_name);
            }
        });

        lStaffManage.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lStaffManage.setForeground(new java.awt.Color(255, 255, 255));
        lStaffManage.setText("Satff Manage");
        lStaffManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lStaffManageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lStaffManageMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lStaffManageMouseClicked(me,Manager_name);
            }
        });

        lLogOut.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lLogOut.setForeground(new java.awt.Color(255, 255, 255));
        lLogOut.setText("Log Out");
        lLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lLogOutMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lLogOutMouseClicked(me);
            }
        });

        customer_login.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        customer_login.setForeground(new java.awt.Color(255, 255, 255));
        customer_login.setText("Customer Login");
        customer_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customer_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customer_loginMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                customer_loginMouseClicked(me,Manager_name);
            }
        });

        customer_signup.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        customer_signup.setForeground(new java.awt.Color(255, 255, 255));
        customer_signup.setText("Customer SignUP");
        customer_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customer_signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customer_signupMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                customer_signupMouseClicked(me,Manager_name);
            }
        });

        lCustomerData.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lCustomerData.setForeground(new java.awt.Color(255, 255, 255));
        lCustomerData.setText("Customer Data");
        lCustomerData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lCustomerDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lCustomerDataMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lCustomerDataMouseClicked(me,Manager_name);
            }
        });

        lHome.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lHome.setForeground(new java.awt.Color(126, 90, 200));
        lHome.setText("Home");
        lHome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout manuLayout = new javax.swing.GroupLayout(manu);
        manu.setLayout(manuLayout);
        manuLayout.setHorizontalGroup(
            manuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lHome)
                .addGap(44, 44, 44)
                .addComponent(lCustomerData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(lRoomManage)
                .addGap(50, 50, 50)
                .addComponent(lStaffManage)
                .addGap(40, 40, 40)
                .addComponent(customer_login)
                .addGap(32, 32, 32)
                .addComponent(customer_signup)
                .addGap(39, 39, 39)
                .addComponent(lLogOut)
                .addGap(25, 25, 25))
        );
        manuLayout.setVerticalGroup(
            manuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(manuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRoomManage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lStaffManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customer_login)
                    .addComponent(customer_signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lLogOut)
                    .addComponent(lCustomerData, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lHome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(manu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 50));

        bgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/reception2.jpeg"))); // NOI18N
        getContentPane().add(bgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // room_manage label here
    private void lRoomManageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRoomManageMouseEntered
        // TODO add your handling code here:
        lRoomManage.setForeground(new java.awt.Color(126,90,200));
        lRoomManage.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.black));
    }//GEN-LAST:event_lRoomManageMouseEntered

    private void lRoomManageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRoomManageMouseExited
        // TODO add your handling code here:
        lRoomManage.setForeground(Color.white);
        lRoomManage.setBorder(null);
    }//GEN-LAST:event_lRoomManageMouseExited

    private void lStaffManageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lStaffManageMouseEntered
        // TODO add your handling code here:
        lStaffManage.setForeground(new java.awt.Color(126,90,200));
        lStaffManage.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.black));
    }//GEN-LAST:event_lStaffManageMouseEntered

    private void lStaffManageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lStaffManageMouseExited
        // TODO add your handling code here:
        lStaffManage.setForeground(Color.white);
        lStaffManage.setBorder(null);
    }//GEN-LAST:event_lStaffManageMouseExited

    private void customer_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_loginMouseEntered
        // TODO add your handling code here:
        customer_login.setForeground(new java.awt.Color(126,90,200));
        customer_login.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.black));
    }//GEN-LAST:event_customer_loginMouseEntered

    private void customer_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_loginMouseExited
        // TODO add your handling code here:
        customer_login.setForeground(Color.white);
        customer_login.setBorder(null);
    }//GEN-LAST:event_customer_loginMouseExited

    private void customer_signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_signupMouseEntered
        // TODO add your handling code here:
        customer_signup.setForeground(new java.awt.Color(126,90,200));
        customer_signup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.black));
    }//GEN-LAST:event_customer_signupMouseEntered

    private void customer_signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_signupMouseExited
        // TODO add your handling code here:
        customer_signup.setForeground(Color.white);
        customer_signup.setBorder(null);
    }//GEN-LAST:event_customer_signupMouseExited

    private void lLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lLogOutMouseEntered
        // TODO add your handling code here:
        lLogOut.setForeground(new java.awt.Color(126,90,200));
        lLogOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.black));
    }//GEN-LAST:event_lLogOutMouseEntered

    private void lLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lLogOutMouseExited
        // TODO add your handling code here:
        lLogOut.setForeground(Color.white);
        lLogOut.setBorder(null);
    }//GEN-LAST:event_lLogOutMouseExited

    private void lCustomerDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCustomerDataMouseEntered
        // TODO add your handling code here:
        lCustomerData.setForeground(new java.awt.Color(126,90,200));
        lCustomerData.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.black));
    }//GEN-LAST:event_lCustomerDataMouseEntered

    private void lCustomerDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCustomerDataMouseExited
        // TODO add your handling code here:
        lCustomerData.setForeground(Color.white);
        lCustomerData.setBorder(null);
    }//GEN-LAST:event_lCustomerDataMouseExited

    private void customer_signupMouseClicked(MouseEvent me,String name) {
       if(me.getSource()==customer_signup) {
           dispose();
           new SignUpForm(name).setVisible(true);
       }
    }

    protected void lRoomManageMouseClicked(MouseEvent me,String name) {
        if(me.getSource()==lRoomManage) {
            dispose();
            new RoomManage(name).setVisible(true);
        }
    }

    protected void lStaffManageMouseClicked(MouseEvent me,String name) {
        if(me.getSource()==lStaffManage) {
            dispose();
            new employee(name).setVisible(true);
        }
    }
    
    protected void customer_loginMouseClicked(MouseEvent me,String name) {
        if(me.getSource()==customer_login) {
            dispose();
            new Login_Form(name).setVisible(true);
        }
    }

    protected void lCustomerDataMouseClicked(MouseEvent me, String manager_name) {
        if(me.getSource()==lCustomerData) {
            dispose();
            new Customer_Data(manager_name).setVisible(true);
        }
    }

    protected void lLogOutMouseClicked(MouseEvent me) {
       if(me.getSource()==lLogOut) {
           int x = JOptionPane.showConfirmDialog(null, "You Are Going To Logout");
           if(x==0) {
                dispose();
                new HomePage().setVisible(true);
            }
       }
    }



    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(Manager_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(Manager_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(Manager_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(Manager_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>
        

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new Manager_Home("").setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg2;
    private javax.swing.JLabel bgimg;
    private javax.swing.JLabel customer_login;
    private javax.swing.JLabel customer_signup;
    private javax.swing.JLabel lCustomerData;
    private javax.swing.JLabel lHome;
    private javax.swing.JLabel lLogOut;
    private javax.swing.JLabel lRoomManage;
    private javax.swing.JLabel lStaffManage;
    private javax.swing.JLabel lmanager;
    private javax.swing.JLabel lwelcome;
    private javax.swing.JPanel manu;
    // End of variables declaration//GEN-END:variables
}
