// package login_register;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
// package login_register;

/**
 *
 * @author admin
 */
public class Manager_LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    boolean email=false,passwword1=false;
    public Manager_LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        lhome = new javax.swing.JLabel();
        lsignup = new javax.swing.JLabel();
        heading1 = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        lemail = new javax.swing.JLabel();
        lpass = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        tpass = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        forgotpass = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 102, 51));

        lhome.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lhome.setForeground(new java.awt.Color(255, 255, 255));
        lhome.setText("Home");
        lhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lhomeMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lhomeMouseClicked(me);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lhomeMouseExited(me);
            }
        });

        lsignup.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lsignup.setForeground(new java.awt.Color(255, 255, 255));
        lsignup.setText("SignUp");
        lsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lsingupMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lsignupMouseClicked(me);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lsignupMouseExited(me);
            }
        });

        heading1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        heading1.setForeground(new java.awt.Color(255, 255, 255));
        heading1.setText("Manager Login");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(845, Short.MAX_VALUE)
                .addComponent(lhome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(heading1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(853, Short.MAX_VALUE)))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lhome)
                    .addComponent(lsignup))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(heading1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(23, 23, 23)))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 50));

        LoginPanel.setBackground(new java.awt.Color(153, 204, 255));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lemail.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lemail.setText("Email :-");
        LoginPanel.add(lemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 23, -1, 24));

        lpass.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lpass.setText("Password:-");
        LoginPanel.add(lpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 98, -1, 24));

        temail.setBackground(new java.awt.Color(153, 204, 255));
        temail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        temail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent ke) {
                temailkeyReleased(ke);
            }
        });

        LoginPanel.add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 54, 213, -1));

        tpass.setBackground(new java.awt.Color(153, 204, 255));
        tpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent ke) {
                tpasskeyReleased(ke);
            }
        });
        LoginPanel.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 129, 213, -1));

        login.setBackground(new java.awt.Color(255, 153, 51));
        login.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                loginActionPerformed(ae);
            }
        });
        LoginPanel.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 172, 95, -1));

        signup.setBackground(new java.awt.Color(255, 153, 51));
        signup.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("SignUp");
        signup.setVisible(false);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                singupActionPerformed(ae);
            }
        });
        LoginPanel.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 172, -1, -1));

        forgotpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forgotpass.setForeground(new java.awt.Color(255, 51, 51));
        forgotpass.setText("Forgot Password?");
        forgotpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 51, 51)));
        forgotpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                forgotpassMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                forgotpassMouseClicked(me);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                forgotpassMouseExited(me);
            }
        });
        
        LoginPanel.add(forgotpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 206, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/Login_img.jpeg"))); // NOI18N
        LoginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 240));

        getContentPane().add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 560, 240));

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));

        heading.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Login as Manager ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(heading)
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 560, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/Bg Image.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // forgot pass l 
    protected void forgotpassMouseExited(MouseEvent me) {
        forgotpass.setForeground(new java.awt.Color(255, 51, 51));
        forgotpass.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
    }

    protected void forgotpassMouseEnterd(MouseEvent e) {
        forgotpass.setForeground(Color.BLUE);
        forgotpass.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLUE));
    }

    protected void forgotpassMouseClicked(MouseEvent me) {
        if(me.getSource()==forgotpass) {
            dispose();
            new manager_forget_pass().setVisible(true);
        }
    }

    // l signup
    protected void lsignupMouseExited(MouseEvent me) {
        lsignup.setForeground(new java.awt.Color(255, 255, 255));
        lsignup.setBorder(null);
    }

    protected void lsingupMouseEnterd(MouseEvent e) {
        lsignup.setForeground(new java.awt.Color(126,90,200));
        lsignup.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
    }

    protected void lsignupMouseClicked(MouseEvent me) {
        if(me.getSource() == lsignup) {
            dispose();
            new Manager_SignUp().setVisible(true);
        }
    }

    // l home lable
    protected void lhomeMouseExited(MouseEvent me) {
        lhome.setForeground(new java.awt.Color(255, 255, 255));
        lhome.setBorder(null);
    }

    protected void lhomeMouseClicked(MouseEvent me) {
        if(me.getSource()==lhome) {
            dispose();
            new HomePage().setVisible(true);
        }
    }

    protected void lhomeMouseEnterd(MouseEvent e) {
        lhome.setForeground(new java.awt.Color(126,90,200));
        lhome.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
    }


    // sign up button
    protected void singupActionPerformed(ActionEvent ae) {
        if(ae.getSource()==signup) {
            dispose();
            new Manager_SignUp().setVisible(true);
        }
    }

    protected void loginActionPerformed(ActionEvent ae) {
        if(tpass.getText().equals("")) {
            JOptionPane.showMessageDialog(login, "Password is Empty", "Input Empty", JOptionPane.WARNING_MESSAGE);
        }
        else if(temail.getText().equals("")) {
            JOptionPane.showMessageDialog(login, "Email is Empty", "Input Empty", JOptionPane.WARNING_MESSAGE);
        }
        else if(email!=true && passwword1!=true) {
            JOptionPane.showMessageDialog(login, "Fill UP Correct", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        }
        else {
            try {
                Connection con = new dbConnection().getDbconnection();
                Statement stm = con.createStatement();
                String sql = "select m_password,m_name,status from manager_details where m_email='"+temail.getText()+"'";
                ResultSet rs = stm.executeQuery(sql);
                if(rs.next()) {
                    final String password = tpass.getText();
                    final String Dpass = rs.getString("m_password");
                    if(password.equals(Dpass)) {
                        if(rs.getBoolean("status")!=false) {
                            JOptionPane.showMessageDialog(login, "Welcome Again Manager", "Welcome", JOptionPane.PLAIN_MESSAGE);
                            if(ae.getSource()==login) {
                                dispose();
                                String [] names = rs.getString("m_name").split(" ");
                                new Manager_Home(names[0]).setVisible(true);
                            }
                        }
                        else {
                            JOptionPane.showMessageDialog(null, "Contact to Admin" , "Alert",JOptionPane.WARNING_MESSAGE);
                        }
                    }
                    else {
                        JOptionPane.showMessageDialog(login, "Incorrect Password", "Wrong Password", JOptionPane.WARNING_MESSAGE);
                    }
                }
                else {
                    JOptionPane.showMessageDialog(login, "Given Details Is Not Found", "Not Found", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                //TODO: handle exception
                System.out.println(e);
            }
        }
    }

    protected void tpasskeyReleased(KeyEvent ke) {
        String PATTERN = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&-+=()])(?=\\S+$).{8,20}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(tpass.getText());
        if (!match.matches()) {
            // JOptionPane.showMessageDialog(null, "Please enter the username");
            tpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            passwword1=false;

        } else {
            passwword1=true;
            tpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        }
    }

    protected void temailkeyReleased(KeyEvent ke) {
        String PATTERN = "^[_A-Za-z0-9-\\+]{6,30}+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(temail.getText());
        if (!match.matches()) {
            // JOptionPane.showMessageDialog(null, "Please enter the username");
            temail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            email=false;

        } else {
            email=true;
            temail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        }
    }

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(Manager_LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(Manager_LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(Manager_LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(Manager_LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new Manager_LoginForm().setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel forgotpass;
    private javax.swing.JPanel header;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel heading1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lemail;
    private javax.swing.JLabel lhome;
    private javax.swing.JButton login;
    private javax.swing.JLabel lpass;
    private javax.swing.JLabel lsignup;
    private javax.swing.JButton signup;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tpass;
    // End of variables declaration//GEN-END:variables
}
