/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
// package hotel_management_system;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.jar.Attributes.Name;

import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author admin
 */
public class Manager_Details extends javax.swing.JFrame {

    /**
     * Creates new form Manager_Details
     */
    public Manager_Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        manu = new javax.swing.JPanel();
        lRoomBookingDetails = new javax.swing.JLabel();
        lStaffDetails = new javax.swing.JLabel();
        lManagersDetails = new javax.swing.JLabel();
        lHome = new javax.swing.JLabel();
        lLogOut = new javax.swing.JLabel();
        SearchPanel = new javax.swing.JPanel();
        tSearch = new javax.swing.JTextField();
        Name = new javax.swing.JRadioButton();
        Email = new javax.swing.JRadioButton();
        PhoneNo = new javax.swing.JRadioButton();
        Search = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        TablePanel = new javax.swing.JScrollPane();
        Manager_Table = new javax.swing.JTable();
        bgimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manu.setBackground(new java.awt.Color(255, 102, 51));

        lRoomBookingDetails.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lRoomBookingDetails.setForeground(new java.awt.Color(255, 255, 255));
        lRoomBookingDetails.setText("Room Details");
        lRoomBookingDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lRoomBookingDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lRoomBookingDetailsMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lRoomBookingDetailsMouseClicked(evt);
            }
        });

        lStaffDetails.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lStaffDetails.setForeground(new java.awt.Color(255, 255, 255));
        lStaffDetails.setText("Staff Details");
        lStaffDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lStaffDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lStaffDetailsMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lStaffDetailsMouseClicked(evt);
            }
        });

        lManagersDetails.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lManagersDetails.setForeground(new java.awt.Color(126, 90, 200));
        lManagersDetails.setText("Managers Details");
        lManagersDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        lHome.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lHome.setForeground(new java.awt.Color(255, 255, 255));
        lHome.setText("Home");
        lHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lHomeMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lHomeMouseClicked(evt);
            }
        });

        lLogOut.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lLogOut.setForeground(new java.awt.Color(255, 255, 255));
        lLogOut.setText("Log Out");
        lLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lLogOutMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lLogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout manuLayout = new javax.swing.GroupLayout(manu);
        manu.setLayout(manuLayout);
        manuLayout.setHorizontalGroup(
            manuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addComponent(lManagersDetails)
                .addGap(57, 57, 57)
                .addComponent(lStaffDetails)
                .addGap(48, 48, 48)
                .addComponent(lRoomBookingDetails)
                .addGap(48, 48, 48)
                .addComponent(lLogOut)
                .addGap(25, 25, 25))
        );
        manuLayout.setVerticalGroup(
            manuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStaffDetails)
                    .addComponent(lHome)
                    .addComponent(lManagersDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lRoomBookingDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lLogOut))
                .addContainerGap())
        );

        getContentPane().add(manu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 40));

        SearchPanel.setBackground(new java.awt.Color(255, 153, 102));

        Name.setBackground(new java.awt.Color(255, 153, 102));
        buttonGroup1.add(Name);
        Name.setText("Name");

        Email.setBackground(new java.awt.Color(255, 153, 102));
        buttonGroup1.add(Email);
        Email.setText("Email");

        PhoneNo.setBackground(new java.awt.Color(255, 153, 102));
        buttonGroup1.add(PhoneNo);
        PhoneNo.setText("Phone No.");

        Search.setBackground(new java.awt.Color(153, 204, 255));
        Search.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent ae) {
                SearchActionPerformed(ae);
            }
        });

        Remove.setBackground(new java.awt.Color(153, 204, 255));
        Remove.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Remove.setForeground(new java.awt.Color(255, 255, 255));
        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent ae) {
                RemoveActionPerformed(ae);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(Name)
                .addGap(18, 18, 18)
                .addComponent(Email)
                .addGap(18, 18, 18)
                .addComponent(PhoneNo)
                .addGap(18, 18, 18)
                .addComponent(tSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(Email)
                    .addComponent(PhoneNo)
                    .addComponent(tSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search)
                    .addComponent(Remove))
                .addContainerGap())
        );

        getContentPane().add(SearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1080, 50));

        TablePanel.setBackground(new java.awt.Color(255, 255, 255));

        Manager_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Phone_No.", "Email", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Manager_Table.setToolTipText("");
        DefaultTableModel atm = (DefaultTableModel)Manager_Table.getModel();
        atm.addTableModelListener(new javax.swing.event.TableModelListener() {
            public void tableChanged(TableModelEvent e) {
                modelevent(e);
            }
        });
        TablePanel.setViewportView(Manager_Table);
        try {
            DefaultTableModel dtm = (DefaultTableModel)Manager_Table.getModel();
            Connection con = new dbConnection().getDbconnection();
            Statement stm = con.createStatement();
            String q = "select * from manager_details";
            ResultSet rs = stm.executeQuery(q);
            while(rs.next()) {
                String[] row = {Integer.toString(rs.getInt("m_id")), rs.getString("m_name"),Long.toString(rs.getLong("phone")), rs.getString("m_email"), Boolean.toString(rs.getBoolean("status"))};
                dtm.addRow(row);
            }
        } catch (Exception e) {
            //TODO: handle exception
            System.out.println(e);
        }

        getContentPane().add(TablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 970, 550));

        bgimg.setBackground(new java.awt.Color(255, 153, 102));
        bgimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/Admin Home.jpg"))); // NOI18N
        getContentPane().add(bgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    protected void lStaffDetailsMouseClicked(MouseEvent evt) {
        if(evt.getSource()==lStaffDetails) {
            dispose();
            new Staff_Details().setVisible(true);
        }
    }

    protected void lRoomBookingDetailsMouseClicked(MouseEvent evt) {
        if(evt.getSource()==lRoomBookingDetails) {
            dispose();
            new Room_Details().setVisible(true);
        }
    }

    protected void lHomeMouseClicked(MouseEvent evt) {
        if(evt.getSource()==lHome) {
            dispose();
            new Admin_Home().setVisible(true);
        }
    }

    protected void lLogOutMouseClicked(MouseEvent evt) {
        if(evt.getSource()==lLogOut) {
            dispose();
            new HomePage().setVisible(true);
        }
    }


    // others here
    protected void RemoveActionPerformed(ActionEvent ae) {
        if(Manager_Table.getSelectedRow()!=-1) {
            try {
                String emails = Manager_Table.getValueAt(Manager_Table.getSelectedRow(), 3).toString();
                Connection con = new dbConnection().getDbconnection();
                Statement stm = con.createStatement();
                String q = "delete from manager_details where m_email='"+emails+"'";
                int x = stm.executeUpdate(q);
                if(x!=0) {
                    JOptionPane.showMessageDialog(null, "record deleted Fine", "Deleted", JOptionPane.PLAIN_MESSAGE);
                    DefaultTableModel dtm = (DefaultTableModel)Manager_Table.getModel();
                    dtm.removeRow(Manager_Table.getSelectedRow());
                }
                else {
                    JOptionPane.showMessageDialog(null, "Not record Deleted Fine", "Something Wrong", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                //TODO: handle exception
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Select Any One Row", "Not Selected", JOptionPane.WARNING_MESSAGE);
        }
    }

    protected void SearchActionPerformed(ActionEvent ae) {
        if(tSearch.getText().equals("")) {
            try {
                DefaultTableModel dtm = (DefaultTableModel)Manager_Table.getModel();
                Connection con = new dbConnection().getDbconnection();
                Statement stm = con.createStatement();
                String q = "select * from manager_details";
                ResultSet rs = stm.executeQuery(q);
                while(dtm.getRowCount()>0)
                dtm.removeRow(dtm.getRowCount()-1);
                while(rs.next()) {
                    String[] row = {Integer.toString(rs.getInt("m_id")), rs.getString("m_name"),Long.toString(rs.getLong("phone")), rs.getString("m_email"), Boolean.toString(rs.getBoolean("status"))};
                    dtm.addRow(row);
                }
            } catch (Exception e) {
                //TODO: handle exception
                System.out.println(e);
            }
        }
        else if(Name.isSelected()==true) {
            try {
                Connection con = new dbConnection().getDbconnection();
                Statement stm = con.createStatement();
                String q = "select m_id,m_name,phone,m_email,status from manager_details where m_name='"+tSearch.getText()+"' ";
                ResultSet rs = stm.executeQuery(q);
                DefaultTableModel dtm = (DefaultTableModel)Manager_Table.getModel();
                while(dtm.getRowCount()>0)
                dtm.removeRow(dtm.getRowCount()-1);
                while(rs.next()) {
                    String[] row = {Integer.toString(rs.getInt("m_id")), rs.getString("m_name"),Long.toString(rs.getLong("phone")), rs.getString("m_email"), Boolean.toString(rs.getBoolean("status"))};
                    dtm.addRow(row);
                }
            } catch (Exception e) {
                //TODO: handle exception
                System.out.println(e);
            }
        }
        else if(PhoneNo.isSelected()==true) {
            try {
                Connection con = new dbConnection().getDbconnection();
                Statement stm = con.createStatement();
                String q = "select m_id,m_name,phone,m_email,status from manager_details where phone="+tSearch.getText()+" ";
                ResultSet rs = stm.executeQuery(q);
                DefaultTableModel dtm = (DefaultTableModel)Manager_Table.getModel();
                while(dtm.getRowCount()>0)
                dtm.removeRow(dtm.getRowCount()-1);
                while(rs.next()) {
                    String[] row = {Integer.toString(rs.getInt("m_id")), rs.getString("m_name"),Long.toString(rs.getLong("phone")), rs.getString("m_email"), Boolean.toString(rs.getBoolean("status"))};
                    dtm.addRow(row);
                }
            } catch (Exception e) {
                //TODO: handle exception
                System.out.println(e);
            }
        }
        else if(Email.isSelected()==true) {
            try {
                Connection con = new dbConnection().getDbconnection();
                Statement stm = con.createStatement();
                String q = "select m_id,m_name,phone,m_email,status from manager_details where m_email='"+tSearch.getText()+"' ";
                ResultSet rs = stm.executeQuery(q);
                DefaultTableModel dtm = (DefaultTableModel)Manager_Table.getModel();
                while(dtm.getRowCount()>0)
                dtm.removeRow(dtm.getRowCount()-1);
                while(rs.next()) {
                    String[] row = {Integer.toString(rs.getInt("m_id")), rs.getString("m_name"),Long.toString(rs.getLong("phone")), rs.getString("m_email"), Boolean.toString(rs.getBoolean("status"))};
                    dtm.addRow(row);
                }
            } catch (Exception e) {
                //TODO: handle exception
                System.out.println(e);
            }
        }
    }

    protected void modelevent(TableModelEvent e) {
        int i = Manager_Table.getEditingRow();
        if(i>=0) {
            String stat =  Manager_Table.getValueAt(i, 4).toString();
            String id = Manager_Table.getValueAt(i, 0).toString();

            // System.out.println( Manager_Table.getValueAt(i, 4));
            try {
                Connection con = new dbConnection().getDbconnection();
                Statement stm = con.createStatement();
                String q = "update manager_details set status = "+stat+" where m_id = "+id+"";
                int x = stm.executeUpdate(q);
                if(x!=0) {
                    JOptionPane.showMessageDialog(null, "updated records of manager", "Fine", JOptionPane.PLAIN_MESSAGE);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Not updated records of manager", "Fine", JOptionPane.WARNING_MESSAGE);
                }
            }
            catch(Exception a) {
                System.out.println(a);
            }
        }
    }

    private void lRoomBookingDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRoomBookingDetailsMouseEntered
        // TODO add your handling code here:
        lRoomBookingDetails.setForeground(new java.awt.Color(126,90,200));
        lRoomBookingDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.black));
    }//GEN-LAST:event_lRoomBookingDetailsMouseEntered

    private void lRoomBookingDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lRoomBookingDetailsMouseExited
        // TODO add your handling code here:
        lRoomBookingDetails.setForeground(Color.white);
        lRoomBookingDetails.setBorder(null);
    }//GEN-LAST:event_lRoomBookingDetailsMouseExited

    private void lStaffDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lStaffDetailsMouseEntered
        // TODO add your handling code here:
        lStaffDetails.setForeground(new java.awt.Color(126,90,200));
        lStaffDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.black));
    }//GEN-LAST:event_lStaffDetailsMouseEntered

    private void lStaffDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lStaffDetailsMouseExited
        // TODO add your handling code here:
        lStaffDetails.setForeground(Color.white);
        lStaffDetails.setBorder(null);
    }//GEN-LAST:event_lStaffDetailsMouseExited

    private void lLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lLogOutMouseEntered
        // TODO add your handling code here:
        lLogOut.setForeground(new java.awt.Color(126,90,200));
        lLogOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.black));
    }//GEN-LAST:event_lLogOutMouseEntered

    private void lLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lLogOutMouseExited
        // TODO add your handling code here:
        lLogOut.setForeground(Color.white);
        lLogOut.setBorder(null);
    }//GEN-LAST:event_lLogOutMouseExited

    private void lHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lHomeMouseEntered
        // TODO add your handling code here:
        lHome.setForeground(new java.awt.Color(126,90,200));
        lHome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, Color.black));
    }//GEN-LAST:event_lHomeMouseEntered

    private void lHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lHomeMouseExited
        // TODO add your handling code here:
        lHome.setForeground(Color.white);
        lHome.setBorder(null);
    }//GEN-LAST:event_lHomeMouseExited

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(Manager_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(Manager_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(Manager_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(Manager_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new Manager_Details().setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Email;
    private javax.swing.JTable Manager_Table;
    private javax.swing.JRadioButton Name;
    private javax.swing.JRadioButton PhoneNo;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Search;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JScrollPane TablePanel;
    private javax.swing.JLabel bgimg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lHome;
    private javax.swing.JLabel lLogOut;
    private javax.swing.JLabel lManagersDetails;
    private javax.swing.JLabel lRoomBookingDetails;
    private javax.swing.JLabel lStaffDetails;
    private javax.swing.JPanel manu;
    private javax.swing.JTextField tSearch;
    // End of variables declaration//GEN-END:variables
}
