/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
// package hotel_management_system;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author admin
 */
public class RE extends javax.swing.JFrame {

    /**
     * Creates new form RE
     */
    boolean tcheck_in=true,tnamec=false;
    public RE(String name,String email) {
        initComponents(name,email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String Manager_name,String CustEmail) {

        jPanel3 = new javax.swing.JPanel();
        lname = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lRoom = new javax.swing.JLabel();
        lPricePerDay = new javax.swing.JLabel();
        lCustIn = new javax.swing.JLabel();
        lCustOut = new javax.swing.JLabel();
        lstay = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        tRoom = new javax.swing.JTextField();
        tPricePerDay = new javax.swing.JTextField();
        tCustIn = new javax.swing.JTextField();
        tstay = new javax.swing.JTextField();
        tCustOut = new javax.swing.JTextField();
        tTotal = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        out = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lRoomBooking1 = new javax.swing.JLabel();
        lRoomOut1 = new javax.swing.JLabel();
        lCustomeRoom = new javax.swing.JLabel();
        lHome1 = new javax.swing.JLabel();
        bgimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        lname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lname.setText("Email:-");

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                searchbActionPerformed(ae);
            }
        });

        lRoom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lRoom.setText("Rooms No. :-");

        lPricePerDay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lPricePerDay.setText("Price per Day:-");

        lCustIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lCustIn.setText("Customer Check In Date:-");

        lCustOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lCustOut.setText("Customer Out Date(Today):-");

        lstay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lstay.setText("No. of Days Stay :-");

        lTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lTotal.setText("Total price :-");

        tRoom.setBackground(new java.awt.Color(153, 204, 255));
        tRoom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        
        // tRoom.setVisible(false);
        tRoom.setEditable(false);


        tPricePerDay.setBackground(new java.awt.Color(153, 204, 255));
        tPricePerDay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tPricePerDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(KeyEvent ke) {
                namekeyReleased(ke);
            }
        });
        // tPricePerDay.setVisible(false);
        tPricePerDay.setEditable(false);


        tCustIn.setBackground(new java.awt.Color(153, 204, 255));
        tCustIn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        
        // tCustIn.setVisible(false);
        tCustIn.setEditable(false);

        tstay.setBackground(new java.awt.Color(153, 204, 255));
        tstay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        
        // tstay.setVisible(false);
        tstay.setEditable(false);

        tCustOut.setBackground(new java.awt.Color(153, 204, 255));
        tCustOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tCustOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(KeyEvent ke) {
                tCustOutkeyReleased(ke);
            }
        });

        tTotal.setBackground(new java.awt.Color(153, 204, 255));
        tTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        

        clear.setBackground(new java.awt.Color(255, 102, 51));
        clear.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText(" Calculate Bill");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                clearActionPerformed(ae);
            }
        });
        clear.setEnabled(false);

        out.setBackground(new java.awt.Color(255, 102, 51));
        out.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        out.setForeground(new java.awt.Color(255, 255, 255));
        out.setText("Customer Out");
        out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                outActionPerformed(ae,Manager_name);
            }
        });
        out.setEnabled(false);

        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(KeyEvent ke) {
                namekeyReleased(ke);
            }
        });
        name.setText(CustEmail);
        tnamec=true;

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(out))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tstay, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                .addComponent(tPricePerDay)
                                .addComponent(tRoom))
                            .addComponent(lPricePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lstay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCustIn)
                            .addComponent(lCustOut)
                            .addComponent(tCustIn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(tCustOut)
                            .addComponent(tTotal))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(lname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lRoom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lCustIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCustIn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPricePerDay)
                            .addComponent(lCustOut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tPricePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCustOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTotal)
                            .addComponent(lstay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tstay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(out))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 187, 800, 390));

        jPanel4.setBackground(new java.awt.Color(255, 102, 51));

        lRoomBooking1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lRoomBooking1.setForeground(new java.awt.Color(255, 255, 255));
        lRoomBooking1.setText("Room Booking");
        lRoomBooking1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lRoomBookingMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lRoomBookingMouseClicked(me);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lRoomBookingMouseExited(me);
            }
        });

        lRoomOut1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lRoomOut1.setForeground(new java.awt.Color(255, 255, 255));
        lRoomOut1.setText("Room Out");
        lRoomOut1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 51)));
        lRoomOut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lRoomOutMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lRoomOutMouseClicked(me,Manager_name,CustEmail);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lRoomOutMouseExited(me);
            }
        });

        lCustomeRoom.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lCustomeRoom.setForeground(new java.awt.Color(255, 255, 255));
        lCustomeRoom.setText("Customize Room");
        lCustomeRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lCustomeRoomMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lCustomeRoomMouseClicked(me,Manager_name,CustEmail);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lCustomeRoomMouseExited(me);
            }
        });

        lHome1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lHome1.setForeground(new java.awt.Color(255, 255, 255));
        lHome1.setText("Home");
        lHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lhomeMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lhomeMouseClicked(me,Manager_name);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lhomeMouseExited(me);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lHome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                .addComponent(lRoomBooking1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(lRoomOut1)
                .addGap(104, 104, 104)
                .addComponent(lCustomeRoom)
                .addGap(60, 60, 60))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRoomBooking1)
                    .addComponent(lRoomOut1)
                    .addComponent(lHome1)
                    .addComponent(lCustomeRoom))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 40));

        bgimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/bg1.jpeg"))); // NOI18N
        getContentPane().add(bgimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // here room out
    protected void lRoomOutMouseExited(MouseEvent me) {
        lRoomOut1.setForeground(new java.awt.Color(255, 255, 255));
        lRoomOut1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 102)));
    }

    protected void lRoomOutMouseClicked(MouseEvent me, String manager_name, String custEmail) {
        
    }

    protected void lRoomOutMouseEnterd(MouseEvent e) {
        lRoomOut1.setForeground(new java.awt.Color(126,90,200));
        lRoomOut1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.BLACK));
    }

    // room booking here
    protected void lRoomBookingMouseExited(MouseEvent me) {
        lRoomBooking1.setForeground(new java.awt.Color(255, 255, 255));
        lRoomBooking1.setBorder(null);
    }

    protected void lRoomBookingMouseClicked(MouseEvent me) {
    }

    protected void lRoomBookingMouseEnterd(MouseEvent e) {
        lRoomBooking1.setForeground(new java.awt.Color(255,000,000));
        lRoomBooking1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.BLACK));
    }

    // customise room here
    protected void lCustomeRoomMouseClicked(MouseEvent me, String manager_name,String CustEmail) {
        if(me.getSource()==lCustomeRoom) {
            dispose();
            new Customise_Room(manager_name,CustEmail).setVisible(true);
        }
    }

    protected void lCustomeRoomMouseExited(MouseEvent me) {
        lCustomeRoom.setForeground(new java.awt.Color(255, 255, 255));
        lCustomeRoom.setBorder(null);
    }

    protected void lCustomeRoomMouseEnterd(MouseEvent e) {
        lCustomeRoom.setForeground(new java.awt.Color(126,90,200));
        lCustomeRoom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.BLACK));
    }

    // home here
    protected void lhomeMouseExited(java.awt.event.MouseEvent me) {
        lHome1.setForeground(new java.awt.Color(255, 255, 255));
        lHome1.setBorder(null);
    }

    protected void lhomeMouseClicked(java.awt.event.MouseEvent me,String name) {
        if(me.getSource()==lHome1) {
            dispose();
            new Manager_Home(name).setVisible(true);
        }
    }

    protected void lhomeMouseEnterd(java.awt.event.MouseEvent e) {
        lHome1.setForeground(new java.awt.Color(126,90,200));
        lHome1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.BLACK));
    }


    // other Funtionality is here
    protected void tCustOutkeyReleased(KeyEvent ke) {
        

        String PATTERN = "^[0-3][0-9]-[0-1][0-9]-[0-9]{4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(tCustOut.getText());
        
        if (!match.matches()) {
            tCustOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            tcheck_in =false;
        } else {
            String s = tCustOut.getText();
            int i = s.indexOf("-");
            char c[] = new char[2];
            c[0] = s.charAt(i+1);
            c[1] = s.charAt(i+2);
            s = new String(c);
            i = Integer.parseInt(s);
            // System.out.println(i);
            if(i<=12) {
                tCustOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
                tcheck_in=true;
            }
            else {
                tcheck_in=false;
                tCustOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            }
        }
    }
    
    protected void clearActionPerformed(ActionEvent ae) {
        lRoomBooking1.setVisible(false);
        lHome1.setVisible(false);
        lRoomOut1.setVisible(false);
        lCustomeRoom.setVisible(false);

        tstay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        try {
            Connection con = new dbConnection().getDbconnection();
            Statement stm = con.createStatement();
            String q = "update customer_total_room_details set date_out=to_date('"+tCustOut.getText()+"','dd-mm-yyyy') where email='"+name.getText()+"' and date_out='1111-11-11'";
            stm.executeUpdate(q); 
            q = "update customer_total_room_details set stay_days= date_out-date_in where email='"+name.getText()+"'";
            stm.executeUpdate(q);
            // q = "select su"
            q = "select stay_days from customer_total_room_details where email='"+name.getText()+"'";
            ResultSet rs = stm.executeQuery(q);
            while(rs.next()) {
                tstay.setText(tstay.getText()+Integer.toString(rs.getInt("stay_days"))+" , ");
            }
            rs =stm.executeQuery("select sum(stay_days) as total_days from customer_total_room_details where email ='"+name.getText()+"'");
            rs.next();
            tstay.setText(tstay.getText()+" = "+Integer.toString(rs.getInt("total_days")));
            q = "select sum(price*stay_days) as total_price_days from customer_total_room_details where email='"+name.getText()+"'";
            rs = stm.executeQuery(q);
            rs.next();
            tTotal.setText(Double.toString(rs.getDouble("total_price_days")));
            // tTotal.setVisible(true);
            // tstay.setVisible(true);
            JOptionPane.showMessageDialog(jButton1, "Calculation is Done !", "Fine ", JOptionPane.PLAIN_MESSAGE);
            clear.setEnabled(false);
            out.setEnabled(true);
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }
    
    protected void outActionPerformed(ActionEvent ae,String Manager_name) {
        StringBuffer s = new StringBuffer();
        String dottedline="";
        Date d = new Date();
        String s2 = d.toString();
        s.append("  "+s2.substring(8,10)+" "+s2.substring(4, 7)+" "+s2.substring(s2.length()-4, s2.length())+"\t"+s2.substring(11, 19));
        for(int i=0 ; i<70*2 ; i++) {
            dottedline+="-";
        }
        s.append("\n"+dottedline);
        s.append("\n");
        s.append("\t\t\tCome Back");
        s.append("\n");
        s.append(dottedline);
        try {
            Connection con = new dbConnection().getDbconnection();
            Statement stm = con.createStatement();
            String q = "select name,phone,email from customer_details where email='"+name.getText()+"'";
            
            ResultSet rs = stm.executeQuery(q);
            Statement stmm = con.createStatement();
            q = "select total_guest from room_reservation_details where email= '"+name.getText()+"'";
            ResultSet rs1 = stmm.executeQuery(q);
            rs.next();
            rs1.next();
            s.append("\n  name : "+rs.getString("name")+"\t\t\tTotal Gust's: "+Integer.toString(rs1.getInt("total_guest"))+" "+"\n  email: "+rs.getString("email")+" \n  phone: "+Long.toString(rs.getLong("phone"))+" \n"); // customer name and details ;
            s.append(dottedline+"\n");

            s.append("  Room No");
            // s.append(String.format("%3s", "|"));
            s.append("\tBed Type");
            // s.append(String.format("%3s", "|"));
            s.append("\tRoom Type");
            // s.append(String.format("%3s", "|"));
            s.append("\tRoom Price");
            // s.append(String.format("%3s", "|"));
            s.append("\tTotal Day's");
            s.append("\tDate-in");
            s.append("\tDate-out");

            s.append("\n"+dottedline+"\n");
            
            q = "select * from customer_total_room_details where email ='"+name.getText()+"'";
            rs = stm.executeQuery(q);
            
            s.append("  ");
            while(rs.next()) {
                
                s.append(Integer.toString(rs.getInt("room_no")));
                q = "select room_type,bed from room_info where room_no="+rs.getInt("room_no")+"";
                rs1 = stmm.executeQuery(q);
                rs1.next();
                s.append("\t"+rs1.getString("bed"));
                s.append("\t"+rs1.getString("room_type"));
                s.append("\t"+rs.getDouble("price"));
                s.append("\t"+rs.getInt("stay_days"));
                SimpleDateFormat datef = new SimpleDateFormat("dd-MM-yyyy");
                s.append("\t"+datef.format(rs.getDate("date_in")));
                s.append("\t"+ datef.format(rs.getDate("date_out")) +"\n");
                s.append("  ");
                // b = rs.next();
            }
            

            s.append("\n"+dottedline+"\n");
            q = "select sum(stay_days) as total_days from customer_total_room_details where email='"+name.getText()+"'";
            rs = stm.executeQuery(q);
            rs.next();
            s.append("  Total Days: "+rs.getInt("total_days")+"\n");
            q = "select sum(price*stay_days) as totalp from customer_total_room_details where email = '"+name.getText()+"'";
            rs = stm.executeQuery(q);
            rs.next();
            s.append("  Total Price: "+rs.getDouble("totalp"));
            s.append("\n"+dottedline+"\n");
            s.append("\t\t\tThank You Visit Again");
            // System.out.println(s);

            q = "delete from customer_total_room_details where email= '"+name.getText()+"'";
            stm.executeUpdate(q);
            q = "select id from customer_details where email ='"+name.getText()+"'";
            rs = stm.executeQuery(q);
            rs.next();
            q = "update room_info set room_status= true , customer_id=null where customer_id="+rs.getInt("id")+"";
            stmm.executeUpdate(q);
            q = "delete from room_reservation_details where customer_id="+rs.getInt("id")+"";
            stmm.executeUpdate(q);
            JTextArea areaa = new JTextArea();
            areaa.setText("");
            areaa.setText(s.toString());
            areaa.print();
            if(ae.getSource()==out) {
                dispose();
                new Manager_Home(Manager_name).setVisible(true);
            }
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }

    protected void namekeyReleased(KeyEvent ke) {
        String PATTERN = "^[_A-Za-z0-9-\\+]{6,30}+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(name.getText());
        if (!match.matches()) {
            
            name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            tnamec=false;
        } else {
            tnamec=true;
            name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        }
    }

    protected void searchbActionPerformed(ActionEvent ae) {
        tCustOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tRoom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tCustIn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        tPricePerDay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        if(name.getText().equals("")) {
            JOptionPane.showMessageDialog(jButton1, "Empty Mail", "Empty Input", JOptionPane.WARNING_MESSAGE);
        }
        else if(tnamec!=true) {
            JOptionPane.showMessageDialog(jButton1, "Invalid Email Format", "please Enter Valid Email Format", JOptionPane.WARNING_MESSAGE);
        }
        else {
            try {
                Connection con = new dbConnection().getDbconnection();
                Statement stm = con.createStatement();
                ResultSet rs = stm.executeQuery("select email,customer_id from room_reservation_details where email='"+name.getText()+"'");
                if(rs.next()) {
                    

                    Statement stmm = con.createStatement();
                    String q = "select room_no,price from customer_total_room_details where email='"+name.getText()+"'";
                    ResultSet rs2 = stmm.executeQuery(q);
                    while(rs2.next()) {
                        tRoom.setText(tRoom.getText()+Integer.toString(rs2.getInt("room_no"))+",");
                        tPricePerDay.setText(tPricePerDay.getText()+Double.toString(rs2.getDouble("price"))+",");
                    }
                    rs2 = stmm.executeQuery("select to_char(min(date_in),'yyyy-mm-dd') as date from customer_total_room_details where email='"+name.getText()+"'");
                    rs2.next();
                    SimpleDateFormat DateFormat = new SimpleDateFormat("dd-MM-yyyy");
                    // System.out.println(DateFormat.format(rs2.getDate("date")));
                    tCustIn.setText(DateFormat.format(rs2.getDate("date")));
                    Date d = new Date();
                    tCustOut.setText(DateFormat.format(d));
                    
                    JOptionPane.showMessageDialog(jButton1, "Record Found", "Successeful", JOptionPane.PLAIN_MESSAGE);
                    jButton1.setEnabled(false);
                    clear.setEnabled(true);
                }
                else {
                    JOptionPane.showMessageDialog(jButton1, "Record are not Found !", "Not Found", JOptionPane.WARNING_MESSAGE);
                }
            }
            catch(Exception e) {
                System.out.println(e);
            }
        }
    }


    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(RE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(RE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(RE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(RE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new RE("name","gadesaurabh215@gmail.com").setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgimg;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lCustIn;
    private javax.swing.JLabel lCustOut;
    private javax.swing.JLabel lCustomeRoom;
    private javax.swing.JLabel lHome1;
    private javax.swing.JLabel lPricePerDay;
    private javax.swing.JLabel lRoom;
    private javax.swing.JLabel lRoomBooking1;
    private javax.swing.JLabel lRoomOut1;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lstay;
    private javax.swing.JTextField name;
    private javax.swing.JButton out;
    private javax.swing.JTextField tCustIn;
    private javax.swing.JTextField tCustOut;
    private javax.swing.JTextField tPricePerDay;
    private javax.swing.JTextField tRoom;
    private javax.swing.JTextField tTotal;
    private javax.swing.JTextField tstay;
    // End of variables declaration//GEN-END:variables
}
