/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
// package login_register;

import java.awt.Color;
import java.awt.event.MouseEvent;
// import java.beans.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author admin
 */
public class SignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    boolean email=false,confi=false,passwword1=false,phone=false,name=false;
    public SignUpForm(String name) {
        initComponents(name);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String Manager_name) {

        Signup_Panel = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        usename = new javax.swing.JTextField();
        phNo = new javax.swing.JTextField();
        e_mail = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        l5 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        signup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        header1 = new javax.swing.JPanel();
        lhome = new javax.swing.JLabel();
        lLogin = new javax.swing.JLabel();
        lcustomerLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(65, 65, 65));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Signup_Panel.setBackground(new java.awt.Color(153,204,255));
        Signup_Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        l2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(0, 0, 0));
        l2.setText("Phone No. :-");

        usename.setBackground(new java.awt.Color(153,204,255));
        usename.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        usename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usenameKeyReleased(evt);
            }
        });

        phNo.setBackground(new java.awt.Color(153,204,255));
        phNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        phNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phNoKeyReleased(evt);
            }
        });

        e_mail.setBackground(new java.awt.Color(153,204,255));
        e_mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        e_mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                e_mailKeyReleased(evt);
            }
        });

        l1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 0, 0));
        l1.setText("Name :-");

        l3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(0, 0, 0));
        l3.setText("E-mail :-");

        l4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(0, 0, 0));
        l4.setText("Confirme Password :-");

        pass1.setBackground(new java.awt.Color(153,204,255));
        pass1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        
        pass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pass1KeyReleased(evt);
            }
        });

        l5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(0, 0, 0));
        l5.setText("Password :-");

        pass2.setBackground(new java.awt.Color(153,204,255));
        pass2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pass2KeyReleased(evt);
            }
        });

        signup.setBackground(new java.awt.Color(255, 102, 51));
        signup.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("Sign Up");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 2, 12)); // NOI18N
        jLabel1.setText("I have an Alredy account.");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        jLabel1.setVisible(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/customer3.jpg"))); // NOI18N

        javax.swing.GroupLayout Signup_PanelLayout = new javax.swing.GroupLayout(Signup_Panel);
        Signup_Panel.setLayout(Signup_PanelLayout);
        Signup_PanelLayout.setHorizontalGroup(
            Signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Signup_PanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Signup_PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(Signup_PanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(Signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Signup_PanelLayout.createSequentialGroup()
                                .addGroup(Signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(l5)
                                        .addComponent(l4)
                                        .addComponent(pass2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                        .addComponent(pass1)
                                        .addComponent(e_mail)
                                        .addComponent(phNo)
                                        .addComponent(usename)))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Signup_PanelLayout.createSequentialGroup()
                                .addComponent(signup)
                                .addGap(43, 43, 43))))))
        );
        Signup_PanelLayout.setVerticalGroup(
            Signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Signup_PanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(usename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(phNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l5)
                .addGap(0, 0, 0)
                .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l4)
                .addGap(0, 0, 0)
                .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Signup_PanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Signup_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 640, 350));

        header1.setBackground(new java.awt.Color(255, 102, 51));

        lhome.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lhome.setForeground(new java.awt.Color(255, 255, 255));
        lhome.setText("Home");
        lhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lhomeMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lhomeMouseClicked(me,Manager_name);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lhomeMouseExited(me);
            }
        });

        lLogin.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lLogin.setForeground(new java.awt.Color(255, 255, 255));
        lLogin.setText("Login");
        lLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e) {
                lLoginMouseEnterd(e);
            }
            public void mouseClicked(java.awt.event.MouseEvent me) {
                lLoginMouseClicked(me,Manager_name);
            }
            public void mouseExited(java.awt.event.MouseEvent me) {
                lLoginMouseExited(me);
            }
        });

        lcustomerLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lcustomerLogin.setForeground(new java.awt.Color(255, 255, 255));
        lcustomerLogin.setText("Customer Registration");

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lcustomerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                .addComponent(lhome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(lLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lhome)
                    .addComponent(lLogin)
                    .addComponent(lcustomerLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("Images/Bg Image.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // l login label here
    protected void lLoginMouseExited(MouseEvent me) {
        lLogin.setForeground(new java.awt.Color(255, 255, 255));
        lLogin.setBorder(null);
    }

    protected void lLoginMouseClicked(MouseEvent me, String manager_name) {
        if(me.getSource()==lLogin) {
            dispose();
            new Login_Form(manager_name).setVisible(true);
        }
    }

    protected void lLoginMouseEnterd(MouseEvent e) {
        lLogin.setForeground(new java.awt.Color(126,90,200));
        lLogin.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
    }


    // l home label fo manager
    protected void lhomeMouseExited(java.awt.event.MouseEvent me) {
        lhome.setForeground(new java.awt.Color(255, 255, 255));
        lhome.setBorder(null);
    }

    protected void lhomeMouseClicked(java.awt.event.MouseEvent me,String name) {
        if(me.getSource()==lhome) {
            dispose();
            new Manager_Home(name).setVisible(true);
        }
    }

    protected void lhomeMouseEnterd(java.awt.event.MouseEvent e) {
        lhome.setForeground(new java.awt.Color(126,90,200));
        lhome.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
    }


    // other code here to executed 
    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        if(usename.getText().equals("")) {
            JOptionPane.showMessageDialog(signup, "Empty Name", "Empty Name", JOptionPane.WARNING_MESSAGE);
        }
        else if(phNo.getText().equals("")) {
            JOptionPane.showMessageDialog(signup, "Empty phone Number", "Empty Phone", JOptionPane.WARNING_MESSAGE);
        }
        else if(e_mail.getText().equals("")) {
            JOptionPane.showMessageDialog(signup, "Empty Email", "Empty Email", JOptionPane.WARNING_MESSAGE);
        }
        else if(pass1.getText().equals("") || pass2.getText().equals("")) {
            JOptionPane.showMessageDialog(signup, "Empty Password Field", "Empty Inputs", JOptionPane.WARNING_MESSAGE);
        }
        else if(email!=true || passwword1!=true || confi!=true || phone!=true || name!=true ) {
            JOptionPane.showMessageDialog(signup, "Some Field not correct", "Invalid Some Inputs", JOptionPane.WARNING_MESSAGE);
        }
        else {
            try {
                Connection con = new dbConnection().getDbconnection();
                Statement stm = con.createStatement();
                String q = "select email from customer_details where email = '"+e_mail.getText()+"' ";
                ResultSet rs = stm.executeQuery(q);
                if(rs.next()!=true) {
                    q = "insert into customer_details(email,name,phone,password) values('"+e_mail.getText()+"' , '"+usename.getText()+"', '"+Long.parseLong(phNo.getText())+"' ,'"+pass1.getText()+"')";
                    int x = stm.executeUpdate(q);
                    if(x!=0) {
                        JOptionPane.showMessageDialog(signup, "Account is Created", "Fine", JOptionPane.PLAIN_MESSAGE);
                        // here call
                        // if(evt.getSource()==signup) {
                        //     dispose();
                        //     new RoomBooing().setVisible(true);
                        // }
                    }
                }
                else {
                    JOptionPane.showMessageDialog(signup,"Details Are Alredy Exits", "Exits", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_signupActionPerformed

    private void usenameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usenameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z\\s]{5,20}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(usename.getText());
        if (!match.matches())
        {
            name=false;
            usename.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255,0,0))));
        }
        else
        {
            name=true;
            usename.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        }
        
    }//GEN-LAST:event_usenameKeyReleased

    private void phNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phNoKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{10}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(phNo.getText());
        if (!match.matches())
        {
            phone=false; 
            phNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255,0,0))));
        }
        else
        {
            phone=true;
            phNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        }
    }//GEN-LAST:event_phNoKeyReleased

    private void e_mailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e_mailKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[_A-Za-z0-9-\\+]{6,30}+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(e_mail.getText());
        if (!match.matches()) {
            // JOptionPane.showMessageDialog(null, "Please enter the username");
            e_mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            email=false;

        } else {
            email=true;
            e_mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        }
    }//GEN-LAST:event_e_mailKeyReleased

    private void pass1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass1KeyReleased
        // TODO add your handling code here:
        String PATTERN = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&-+=()])(?=\\S+$).{8,20}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(pass1.getText());
        if (!match.matches()) {
            // JOptionPane.showMessageDialog(null, "Please enter the username");
            pass1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            pass2.setText("");
            passwword1=false;
            confi=false;
        } else {
            passwword1=true;
            pass1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
        }
    }//GEN-LAST:event_pass1KeyReleased

    private void pass2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass2KeyReleased
        // TODO add your handling code here:
        String PATTERN = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&-+=()])(?=\\S+$).{8,20}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(pass2.getText());
        if (!match.matches()) {
            // JOptionPane.showMessageDialog(null, "Please enter the username");
            pass2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            confi=false;
        } else {
            String s =pass1.getText();
            String s2 = pass2.getText();
            if(s.equals(s2)) {
                pass2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 0)));
                confi = true;
            }
            else {
                confi=false;
                pass2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, (new java.awt.Color(255, 0, 0))));
            }
        }
        
    }//GEN-LAST:event_pass2KeyReleased

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new SignUpForm("").setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField e_mail;
    private javax.swing.JPanel header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lcustomerLogin;
    private javax.swing.JLabel lhome;
    private javax.swing.JPanel Signup_Panel;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JTextField phNo;
    private javax.swing.JButton signup;
    private javax.swing.JTextField usename;
    // End of variables declaration//GEN-END:variables
}
